### ISSUE TITLE
Unable to inject helloWorld.js to SC Homepage

### ISSUE THREAD

**Issue by MarcusICL2** [ibmcnxdev/customizer#12]
Hi Team,

I am on SC L2 Support Team. 
Currently, attempting to test a simple extension, but unable to get the helloWorld.js injected to our SC Connections test org.

Here is json:
{
  "name": "Homepage Customization",
  "title": "Introductory Customizer App",
  "description": "Inserts text into IBM Connections Homepage",
  "services": [
    "Customizer"
  ],
  "extensions": [
    {
      "payload": {
        "include-files": [
          "helloWorld/helloWorld.user.js"
        ],
	      "include-repo":{
	       "name": "global-samples"
	     }
      },
      "name": "Hello World Extension",
      "type": "com.ibm.customizer.ui",
      "path": "homepage"
    }
  ]
}

Is this not working anymore?
Should there be application ids and if so would a pull request be necessary?
Should include-repo point to "customizer" and not "global-samples" (as that repo doesn't seem to exist)?

Any assistance is greatly appreciated! @padraic-edwards @MartinDonnelly

**Comment by ibmcndev** [comment]
Hi Marcus,
What environment are you testing on, apps.na or apps.ce or elsewhere? Has your org been enabled for Customizer ?

The JSON you have above should work. Did you create it in the "Pink" App registry ? Have you seen this video?
https://www.youtube.com/watch?v=sPpUqhalkiA

Thanks,
Padraic

**Comment by MarcusICL2** [comment]
Hello Padraic,

Thanks for the feedback.

I am testing on apps.na.

Our test org id is 20143698.

Not sure, how can I confirm if this org has been enabled for Customizer?
Would it be in subscription?

I see we have the new Apps Manager (Pink Appregistry) option and tried
using it but that did not work.

Not sure how to get "id" for json and it won't let me use just the sample
code from customizer repo.

Someone else tried testing with similar json that has "id" key/value but
that did not work either.

I watch the video as I am not sure if this org was involved in pilot
program.

Any further assistance is greatly appreciated!

Thanks!

                                                               
 IBM           Marcus J. Felder                 Professional   
 Collaboration Staff Software Engineer          Support Badge  
 Solutions     North America Software Support                  
               for Connections                                 
               IBM Collaboration Solutions                     
               mjfelder@us.ibm.com                             
               11501 Burnet Road Austin, Texas                 
               78758 United States                             
                                                               
  ICS Support                                                  
     Blog                                                      
 Collaboration                                                 
 Services Blog                                                 
  ICS Quality                                                  
    Survey                                                     
  ICS Support                                                  
   Facebook                                                    
  ICS Support                                                  
 Twitter  ICS                                                  
   Services                                                    
    Twitter

**Comment by MarcusICL2** [comment]
Hello Padraic,

Thanks for the feedback.

I am testing on apps.na.

Our test org id is <redacted_see_email>.

Not sure, how can I confirm if this org has been enabled for Customizer?  Would it be in subscription?

I see we have the new Apps Manager (Pink Appregistry) option and tried using it but that did not work.

Not sure how to get "id" for json and it won't let me use just the sample code from customizer repo.

Someone else tried testing with similar json that has "id" key/value but that did not work either.

I watch the video as I am not sure if this org was involved in pilot program.

Any further assistance is greatly appreciated!

Thanks!

**Comment by ibmcndev** [comment]
Hi Marcus,
Please email ibmcndev@us.ibm.com and ask for your org to enabled for Customizer as I do not believe it is enabled. In part 3 of the readme, we explain what you need to send to that email address.

https://github.com/hclcnx/customizer/blob/master/README.md

Thanks,
Padraic

**Comment by MarcusICL2** [comment]
Sent...
Do you provision Customizer?
Just curious how long this process takes?
Thanks!

**Comment by ibmcndev** [comment]
The Customizer enablement process usually takes 24 hours.

**Comment by MarcusICL2** [comment]
Customizer has been enabled and the HelloWorld extension is now working...please close and thanks for the support!
