### ISSUE TITLE
Do you have any samples that show how to make a customization to the metrics area of a Community?

### ISSUE THREAD

**Issue by lizhecht** [ibmcnxdev/customizer#14]
I noticed when looking through the IBMConnectionsCustomizer.pdf there is no  path to identify customization to the Metrics application.  Do you have any samples of Customizations which would apply to the Metrics page? can Customers use the math "metrics"? Thanks,

**Comment by MarcusICL2** [comment]
@padraic-edwards does customizer allow us to inject code to Community Metrics?  We noticed that there is no path for Metrics and global is not working.  Also noticed that Community Metrics involves hikari.css and not communities.css for styling.  Any assistance is greatly appreciated!

**Comment by ibmcndev** [comment]
Metrics is not a supported page that can be customized at the moment.

**Comment by MarcusICL2** [comment]
Ok thanks!

**Comment by lizhecht** [comment]
What about overall global theme? Does the theme which is injected into the Connections Cloud get inherited in the metrics UI?

**Comment by lizhecht** [comment]
Please let me know if this is what you mean:
Communities has a overall theme with a Blue theme on the navigation bar:
![communtiesui](https://user-images.githubusercontent.com/29661113/36816882-3ae0474e-1cad-11e8-80f0-ff4bd5209b2c.jpg)
But metrics seems to only display the default theme provided on the cloud:
![metrics ui](https://user-images.githubusercontent.com/29661113/36816907-5713693c-1cad-11e8-96a9-e5fc5032735b.jpg)
Is there no change to the metrics UI even when customizer is used to change the Global UI like the nav bar?

**Comment by ibmcndev** [comment]
Yes, metrics UI is not supported currently so doesn't work even when you use global.

**Comment by ibmcndev** [comment]
Metrics is not a supported path

**Comment by ibmcndev** [comment]
That was meant to be "metrics" is now a supported path :-)
