### ISSUE TITLE
Customizations not working

### ISSUE THREAD

**Issue by GSchwede** [ibmcnxdev/customizer#9]
I can't get the following to work. I am connecting to my repository, can you see anything wrong with the script?

{
    "id": "f0e98ef0-f260-11e7-8525-f353cd48b5e0",
    "name": "News River Sectioned Sample",
    "title": "News River Sectioned Sample",
    "description": "Draws news river in sections surrounded with border",
    "services": [
        "Customizer"
    ],
    "extensions": [
        {
            "id": "71a87731-aaf4-4107-80a9-1b9c3132b8e8",
            "name": "News River Sectioned Extension",
            "type": "com.ibm.customizer.ui",
            "payload": {
                "include-files": [
                    "FBConnectionsCustomization/newsRiverSectioned.user.js"
                ]
            },
            "path": "homepage",
            "application": "News River Sectioned Sample"
        }
    ]
}

**Comment by padraic-edwards** [comment]
Hi,
You need to include the repo name and change the file name. try this

{
"id": "f0e98ef0-f260-11e7-8525-f353cd48b5e0",
"name": "News River Sectioned Sample",
"title": "News River Sectioned Sample",
"description": "Draws news river in sections surrounded with border",
"services": [
"Customizer"
],
"extensions": [
{
"id": "71a87731-aaf4-4107-80a9-1b9c3132b8e8",
"name": "News River Sectioned Extension",
"type": "com.ibm.customizer.ui",
"payload": {
"include-files": [
"newsRiverSectioned.user.js"
],
"include-repo":{
"name":"FBConnectionsCustomization"
}
},
"path": "homepage",
"application": "News River Sectioned Sample"
}
]
}

Thanks,
Padraic

**Comment by GSchwede** [comment]
this worked, thanks so much!!
